### ISSUE TITLE
VM does not restart

### ISSUE THREAD

**Issue by gjongeneel** [sg3-141-592/AzStartStop#4] opened 2023-09-18 17:54 UTC
Hi,

I would like to start by saying that this a very promising and useful tool. It is actually something that Microsoft should provide. 

I have one issue, however. I configured this tool for my test subscription, in which only 3 VMs are present. I configured a start/stop schedule for two VMs; one is working, the other one for some reason is not. I cannot see why there would be a difference between the two VMs. Obviously, the same MI is used for both VMs.

**Comment by sg3-141-592** [comment] 2023-09-18 18:16
Hey there @gjongeneel , thanks for trying out the app and raising this issue. A couple of places where there might be some info that can help diagnose the issue.

Can you open the resource group where you've got AzStartStop installed, and open the "Application Insights" in the resource group.

Can you open the "Failures" tab and see if there's anything in there since you installed the app. Of particular interest is errors around `StartStop` Operation which is what does the turning on and off.

<img width="530" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/0fc66ef9-1acd-4573-84b1-7fc96a516c13">

If there are any errors of note can you share them. Most useful are the Exceptions, so anything that looks like this

<img width="607" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/943f519e-b411-47bc-b90c-04ff9e8944e3">

Also can you go the VM that has the issue and let me know what the values are for `vm-stop-schedule` and `vm-start-schedule` please

<img width="488" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/f35fb96d-f264-4485-86ca-05bb9ac65176">

I'm thinking in the background of options to more easily surface errors to users so they can share them and get them fixed.

**Comment by JClarke90** [comment] 2023-09-18 23:55
I'll add to this one too as I noticed my VM also didn't start.

Tags are there although should the cron expression be using 6 sections not five? I thought the first one was seconds. 

![image](https://github.com/sg3-141-592/AzStartStop/assets/12259768/63d6a2a6-83de-4f8d-8ea5-16412937872b)

But no failures in insights, you can see it tried to do something but I've never used insights before so can't really dig deeper.

![image](https://github.com/sg3-141-592/AzStartStop/assets/12259768/8c6b5535-9a3e-4805-9f7e-7584b2422763)

**Comment by gjongeneel** [comment] 2023-09-19 15:46
Hi Sean,

Thanks for your fast reply. I do not see any errors in the failures tab.

[image: image.png]

The tags seem to apply correctly as well. And yesterday, I changed the
schedule from the failing machine to the exact same as the
successful machine and it started working.

Changed it from original values (ManagementVM failing):
[image: image.png]
Changed it new values (no other changes, both VMs successful):
[image: image.png]
I will try & change it back to the original values and check the results.
The tags changed to the corresponding values as far as I can see:

[image: image.png]
I will verify tomorrow if the Start/Stop continues working.

Thanks!

**Comment by sg3-141-592** [comment] 2023-09-19 15:47
Hey @JClarke90 interesting screenshot. It looks like the issue might be that the `StartStop` function isn't running in your deployment. Where you have a flat line for the  "Request count" on that diagram I have the `StartStop` function triggering every 15 mins. And there's a very low execution count overall (36 total executions compared to at least 96 I'd expect to see in an hour).

![image](https://github.com/sg3-141-592/AzStartStop/assets/5122866/ace61068-896d-4ecb-bb86-b29fe5109064)

I'm just looking for potential areas that could cause the StartStop behaviour to not execute on the expected schedule.

I'm wonder if this is a "[trigger syncing](https://learn.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies?tabs=linux#trigger-syncing)" issue. If so changes to the underlying scheduling code might require restarts to keep working correctly.

@JClarke90 could you restart your function app deployment? Then give it an hour or so then look in App Insights again and see if you get a pattern of a "Request count" that looks more like my diagram above?

![image](https://github.com/sg3-141-592/AzStartStop/assets/5122866/2aebcae6-eaa3-42ea-9440-9818879d1d2b)

**Comment by sg3-141-592** [comment] 2023-09-19 16:06
Hey @gjongeneel , thanks for taking the time to investigate and provide a recreation, Your screenshots are not showing on your comment correctly. Do you mind re-attaching or including as plain text?

![image](https://github.com/sg3-141-592/AzStartStop/assets/5122866/a0646dfc-af1a-4bef-adf3-1ff58cbe0f1f)

Also what Timezone setting are you using currently?

From that I can try and recreate on my side, the might be some issues in the schedule handling logic.

**Comment by gjongeneel** [comment] 2023-09-19 16:16
No failures:
<img width="920" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/4f6371f4-dda3-409a-a274-2dbae3b64354">

This schedule did not work:
<img width="627" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/25d4e65a-7b57-4517-90bf-ebe115c89e1c">

Worked for both VMs:
<img width="514" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/67de8613-ea11-4b26-83bd-e99fd352fcc9">

Tags when schedule was failing:
<img width="561" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/f4bacc1a-3d43-40b1-93a5-28531e552ae5">

Current Settings:
<img width="493" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/b29570b1-77c3-4d64-b61e-9c6dc6ab42a8">

Like I said, I've changed the schedule back to the failing one and will test again (check tomorrow).

**Comment by gjongeneel** [comment] 2023-09-19 16:27
Some other questions concerning the related storage account:

Is there a specific reason for it being v1?
<img width="593" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/c0c4cf26-7b07-415e-bd49-d36cab608524">

Is Blob anonymous access required? Is storage account key access required?
<img width="176" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/9b5eb9e6-1fca-45bb-907c-088a42c821b4">

Can we increase TLS version without issues?
<img width="134" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/2eb24a0a-c445-43a1-a61d-956ad77edca0">

**Comment by gjongeneel** [comment] 2023-09-19 16:30
Sorry, I was just thinking that may be I should have opened a new issue for these specific questions... Sorry!

**Comment by sg3-141-592** [comment] 2023-09-19 19:57
No worries @gjongeneel , I've put this onto #8 . Thanks for identifying this, this sort of early feedback is really critical to getting us into a healthy state so we can put a version 1.0 out 🙂

**Comment by gjongeneel** [comment] 2023-09-21 11:20
It seems that the schedule (ManagementVM) below does not work. When I changed the schedule to be the same as AVDSH-1 it started working and after I changed it back to the setting shown, it stopped again. I guess there is an issue with time (may be after 12:00 AM?) and the selected Timezone?  
<img width="791" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/25dff9ae-b5db-45bd-aaee-8a02134d45d0">

**Comment by sg3-141-592** [comment] 2023-09-21 11:42
Hey @gjongeneel , this issue is related to the fact that the Azure Function that applies the start stop only runs every 15 minutes currently. So it'll be unable to deal with a 5 minute window. It's likely triggering around 23:56, seeing the VMs are in a stopped state and thinking that everything is the right state.

I'm working on adding some validation into the UI to enforce a minimum time between schedules so that users can see this detail.

And I'll improve the frequency of the start/stop commands in the background (down to around 5 mins). The current long 15 minute interval between running start/stop is caused by the fact I start/stop VMs in a blocking way which is very slow (you have to wait for one VM to shutdown before you deal with the next on). I need to make the start/stop commands execute asynchronously so that we don't have these timing issues.

**Comment by gjongeneel** [comment] 2023-09-21 11:58
Thanks for the feedback. However, the VM is not started at all (and not stopped for that matter). The Activity log is empty with that schedule. I just tried another schedule 
<img width="97" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/217ece46-d22a-466c-a4a4-e451fb8f635a">
And that seem to work
<img width="396" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/18477985/1686ba9d-1338-479d-adac-911f87633be4">
Times can fluctuate a bit, but that's no real issue, I guess. I'll keep your remarks in mind.

My schedule with only a few minutes between start and stop is probably not a 'real life' scenario. Most times you will not start a VM for only some minutes. This is just a Visual Studio subscription and me trying to save on monthly budget ;-)

**Comment by sg3-141-592** [comment] 2023-09-21 19:17
I've just pushed a new version which implements a minimum time window #9 . The schedule setter now enforces a minimum time window of 30 minutes.

<img width="503" alt="image" src="https://github.com/sg3-141-592/AzStartStop/assets/5122866/19e13910-efc3-4bb7-9290-473c656490b4">

I've also increased the frequency of the Start/Stop to every 5 minutes and made the starting and stopping multiple VMs asynchronous. So hopefully that'll give improved performance.

The behaviour you're seeing @gjongeneel was around the Start/Stop function only getting called every 15 minutes. A quick illustration, the Start/Stop function looks at the schedule and decides if VMs are in the state it expects for their time window. So with a short time window and some unlucky timing the VM would never get started.

![image](https://github.com/sg3-141-592/AzStartStop/assets/5122866/f767cda9-5b15-4513-a066-ded96995bcd7)

The new version should happen automatically for you, but you can check you're on the new version by looking and the settings and checking for "Release 1.2-preview".

**Comment by gjongeneel** [comment] 2023-09-22 08:26
Yes, version has been updated automatically. Thanks for the explanation.

**Comment by sg3-141-592** [comment] 2023-12-05 19:23
Closing for now as we've got the minimum time window in place for start stop windows to get around this not stopping issue.

**Closed as completed by sg3-141-592** 2023-12-05 19:23 UTC
Labels: bug
